extends Node
## Audio manager (autoload "Sound").
##
## Music is two synchronised stems that loop forever across scene changes:
##   calm  - the garden theme
##   tense - the chase layer; faded in whenever a teddy notices / chases MNKI
## plus a quiet garden ambience loop and a pool of one-shot sound effects.
##
## Usage from any script:
##   Sound.play("pickup_apple")                       # one-shot
##   Sound.play("step1", 0.6, 1.0, 0.08)              # volume, pitch, random pitch jitter
##   Sound.play_dist("alert", distance_px, max_px)    # fades out with distance
##   Sound.set_tension(0.0 .. 1.0)                    # music intensity
##   Sound.set_duck(true)                             # muffle the music (pause / win / lose)
##
## Sounds are generated by tools/make_audio.py into Audio/*.wav.

const AUDIO_DIR := "res://Audio/"
const POOL_SIZE := 20

const SFX_NAMES: Array[String] = [
    "ui_hover", "ui_click", "pause_open", "pause_close", "swap", "chirp", "snip", "scrape",
    "rustle", "disarm_tick", "disarm_done", "danger", "pickup_apple", "pickup_pear",
    "exit_open", "locked", "command", "deny", "notice", "alert", "caught", "harmed",
    "guard_step", "step1", "step2", "step3", "step_wood1", "step_wood2", "flap", "win", "lose",
]

var _streams: Dictionary = {}
var _pool: Array[AudioStreamPlayer] = []
var _next: int = 0
var _last_play: Dictionary = {}

var _calm: AudioStreamPlayer
var _tense: AudioStreamPlayer
var _amb: AudioStreamPlayer
var _lowpass: AudioEffectLowPassFilter

var _tension_target: float = 0.0
var _tension: float = 0.0
var _duck_target: float = 0.0
var _duck: float = 0.0
var _menu_mode: bool = true


func _ready() -> void:
    process_mode = Node.PROCESS_MODE_ALWAYS
    _make_buses()
    apply_volumes()

    for n in SFX_NAMES:
        var s: AudioStream = _load_stream("%ssfx_%s.wav" % [AUDIO_DIR, n])
        if s != null:
            _streams[n] = s

    for i in range(POOL_SIZE):
        var p := AudioStreamPlayer.new()
        p.bus = "SFX"
        add_child(p)
        _pool.append(p)

    _calm = _make_loop_player("music_calm.wav", "Music")
    _tense = _make_loop_player("music_tense.wav", "Music")
    _amb = _make_loop_player("ambience.wav", "Ambience")
    _tense.volume_db = -80.0

    # every Button in the whole game gets hover / click sounds automatically
    get_tree().node_added.connect(_on_node_added)


# ------------------------------------------------------------------ buses
func _make_buses() -> void:
    for n in ["Music", "SFX", "Ambience"]:
        if AudioServer.get_bus_index(n) == -1:
            AudioServer.add_bus()
            var i: int = AudioServer.bus_count - 1
            AudioServer.set_bus_name(i, n)
            AudioServer.set_bus_send(i, "Master")
    _lowpass = AudioEffectLowPassFilter.new()
    _lowpass.cutoff_hz = 20500.0
    AudioServer.add_bus_effect(AudioServer.get_bus_index("Music"), _lowpass)


func apply_volumes() -> void:
    AudioServer.set_bus_volume_db(0, _db(PlayerData.vol_master))
    AudioServer.set_bus_mute(0, PlayerData.muted)
    AudioServer.set_bus_volume_db(AudioServer.get_bus_index("Music"), _db(PlayerData.vol_music))
    AudioServer.set_bus_volume_db(AudioServer.get_bus_index("SFX"), _db(PlayerData.vol_sfx))
    AudioServer.set_bus_volume_db(AudioServer.get_bus_index("Ambience"), _db(PlayerData.vol_sfx))


func _db(v: float) -> float:
    if v <= 0.001:
        return -80.0
    return linear_to_db(v)


# --------------------------------------------------------------- loading
func _load_stream(path: String) -> AudioStream:
    if ResourceLoader.exists(path):
        return load(path) as AudioStream
    # not imported yet (e.g. running without the editor): read the plain WAV ourselves
    if FileAccess.file_exists(path):
        return _parse_wav(path)
    return null


func _parse_wav(path: String) -> AudioStreamWAV:
    var f := FileAccess.open(path, FileAccess.READ)
    if f == null:
        return null
    var bytes: PackedByteArray = f.get_buffer(f.get_length())
    f.close()
    var rate: int = 22050
    var data := PackedByteArray()
    var pos: int = 12
    while pos + 8 <= bytes.size():
        var id: String = bytes.slice(pos, pos + 4).get_string_from_ascii()
        var size: int = bytes.decode_u32(pos + 4)
        if id == "fmt ":
            rate = bytes.decode_u32(pos + 12)
        elif id == "data":
            data = bytes.slice(pos + 8, pos + 8 + size)
        pos += 8 + size + (size & 1)
    if data.is_empty():
        return null
    var w := AudioStreamWAV.new()
    w.format = AudioStreamWAV.FORMAT_16_BITS
    w.mix_rate = rate
    w.stereo = false
    w.data = data
    return w


func _make_loop_player(file: String, bus: String) -> AudioStreamPlayer:
    var p := AudioStreamPlayer.new()
    p.bus = bus
    add_child(p)
    var s: AudioStream = _load_stream(AUDIO_DIR + file)
    if s != null:
        _set_loop(s)
        p.stream = s
    return p


func _set_loop(s: AudioStream) -> void:
    if s is AudioStreamWAV:
        var w: AudioStreamWAV = s
        # get_length() is right for every import format (PCM, ADPCM, QOA), unlike the raw byte size
        w.loop_mode = AudioStreamWAV.LOOP_FORWARD
        w.loop_begin = 0
        w.loop_end = int(round(w.get_length() * float(w.mix_rate)))
    elif s is AudioStreamOggVorbis:
        (s as AudioStreamOggVorbis).loop = true


# ----------------------------------------------------------------- music
## Start the music (no-op if it is already playing, so it carries across scenes).
func ensure_music() -> void:
    if _calm.stream == null or _calm.playing:
        return
    _calm.play()
    if _tense.stream != null:
        _tense.play()
    if _amb.stream != null:
        _amb.play()


## "menu" = fuller music, quiet ambience.  "game" = normal mix.
func set_mode(mode: String) -> void:
    _menu_mode = mode == "menu"
    if _menu_mode:
        _tension_target = 0.0
        _duck_target = 0.0


func set_tension(v: float) -> void:
    _tension_target = clampf(v, 0.0, 1.0)


func set_duck(on: bool) -> void:
    _duck_target = 1.0 if on else 0.0


func _process(delta: float) -> void:
    var rate: float = 1.1 if _tension_target > _tension else 0.35
    _tension = move_toward(_tension, _tension_target, delta * rate)
    _duck = move_toward(_duck, _duck_target, delta * 2.5)
    var gain: float = (1.0 - 0.65 * _duck) * (0.9 if _menu_mode else 0.6)
    _calm.volume_db = _db(gain * (1.0 - 0.8 * _tension))
    _tense.volume_db = _db(gain * _tension * 1.15)
    _amb.volume_db = _db((0.3 if _menu_mode else 0.75) * (1.0 - 0.5 * _duck))
    _lowpass.cutoff_hz = lerpf(20500.0, 1100.0, _duck)


# ------------------------------------------------------------------- sfx
func play(snd: String, vol: float = 1.0, pitch: float = 1.0, jitter: float = 0.0) -> void:
    if not _streams.has(snd):
        return
    var now: int = Time.get_ticks_msec()
    var last: int = int(_last_play.get(snd, -1000))
    if now - last < 35:
        return          # same sound twice in one frame-ish: skip
    _last_play[snd] = now
    var p: AudioStreamPlayer = _pool[_next]
    for i in range(POOL_SIZE):                       # prefer a voice that is idle
        var cand: AudioStreamPlayer = _pool[(_next + i) % POOL_SIZE]
        if not cand.playing:
            p = cand
            _next = (_next + i) % POOL_SIZE
            break
    _next = (_next + 1) % POOL_SIZE
    p.stream = _streams[snd]
    p.volume_db = _db(vol)
    p.pitch_scale = maxf(0.1, pitch * (1.0 + randf_range(-jitter, jitter)))
    p.play()


## Plays "<prefix>1" .. "<prefix><count>" at random (footsteps etc.).
func play_rand(prefix: String, count: int, vol: float = 1.0, pitch: float = 1.0, jitter: float = 0.06) -> void:
    play("%s%d" % [prefix, randi_range(1, count)], vol, pitch, jitter)


## Like play(), but quieter the further away the source is.
func play_dist(snd: String, dist_px: float, max_px: float, vol: float = 1.0, floor_gain: float = 0.0) -> void:
    var k: float = clampf(1.0 - dist_px / max_px, 0.0, 1.0)
    k = maxf(k * k, floor_gain)
    if k < 0.04:
        return
    play(snd, vol * k, 1.0, 0.04)


# ----------------------------------------------------------------- input
func _unhandled_input(event: InputEvent) -> void:
    if event.is_action_pressed("mute"):
        PlayerData.muted = not PlayerData.muted
        PlayerData.save_all()
        apply_volumes()
        if not PlayerData.muted:
            play("ui_click", 0.6)


func _on_node_added(n: Node) -> void:
    if n is BaseButton:
        var b: BaseButton = n
        b.mouse_entered.connect(_on_button_hover.bind(b))
        b.pressed.connect(_on_button_pressed)


func _on_button_hover(b: BaseButton) -> void:
    if not b.disabled:
        play("ui_hover", 0.7)


func _on_button_pressed() -> void:
    play("ui_click", 0.8)
